---
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: set storage pool
      shell: /tmp/virsh_config.sh

    - name: OPNsense wird heruntergeladen und entpackt
      unarchive:
        src: http://130.61.250.134/site/daten/OPNsense.tar.gz
        dest: /daten/vm
        remote_src: yes

    - name: Import OPNsense 
      become: yes
      shell: virsh define /daten/vm/OPNsense/OPNsense.xml

    - name: start OPNsense
      virt:
        name: OPNsense
        state: running

    - name: OPNsense enable Autostart 
      shell: virsh autostart OPNsense
